### ISSUE TITLE
Cannot load library directly from node

### ISSUE THREAD

**Issue by djelic** [plantain-00/expression-engine#3]
Hi,

first of all, great library! One thing though, library is not compiles to work from node without TypeScript. Consider setting `importHelpers: false` in `tsconfig.base.json` since setting it to true adds dependency on `tslib`.

#### Code(if relevant):

```sh
yarn add expression-engine
```

```js
const ee = require('expression-engine')
```

#### Expected:

To load expression-engine successfully.

#### Actual:

```
Thrown:
{ Error: Cannot find module 'tslib'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18) code: 'MODULE_NOT_FOUND' }
```

**Comment by plantain-00** [comment]
v1.7.4 should fix this.
`importHelpers: true` will not inline helper functions, so will reduce the generated js file size, it's better for frontend usage, so I just added `tslib` as a dependency to fix this.

**Comment by djelic** [comment]
Can confirm it works, thanks!
