### ISSUE TITLE
Avoid common security risks

### ISSUE THREAD

**Issue by OpportunityLiu** [plantain-00/expression-engine#5]
#### Code(if relevant):

```
import { tokenizeExpression, parseExpression, evaluateExpression, printExpression } from "expression-engine";

const tokens = tokenizeExpression(`(a => a).constructor("return this")().alert(12)`)
const ast = parseExpression(tokens)
const result = evaluateExpression(ast, { b: 2 })
const expression = printExpression(ast)
```

#### Expected:

Access to special members in the prototype chain should be avoided to prevent common attacks.

For reference: https://github.com/josdejong/mathjs/blob/47a493d70ac92daa47b26f9eea88513a7efa4408/src/utils/customs.js

**Comment by plantain-00** [comment]
v1.8.2 should fix this
